### ISSUE TITLE
Test builds with newer compilers (gcc13, clang16, icpx2023.2...)

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#734]
Test builds with newer compilers (gcc13, clang16, icpx2023.2...)

Just a reminder, as some of these have recently been advertised.

**Comment by valassi** [comment]
Note, for the cern cvmfs installations

- icpx2023.2 seems to be working ok (it is based internally on clang17)

- clang16 with cuda120 is giving this build error (NB it is unsupported there)
```
ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -O3 -lineinfo -I. -I../../src -I/usr/local/cuda-12.0/include/ -DUSE_NVTX -gencode arch=compute_70,code=compute_70 -gencode arch=compute_70,code=sm_70 -use_fast_math -std=c++17  -ccbin /data/avalassi/GPU2023/madgraph4gpuX/tools/compilers/mg-lcg-clang++-16.0.3 -allow-unsupported-compiler -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -Xcompiler -fPIC -c -x cu Parameters_sm.cc -o Parameters_sm_cu.o
/cvmfs/sft.cern.ch/lcg/releases/gcc/13.1.0-b3d18/x86_64-el9/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../include/c++/13.1.0/type_traits(1543): error: identifier "__remove_cv" is undefined
```

- clang16 with CUDA_HOME=none gives this build error
```
ccache /data/avalassi/GPU2023/madgraph4gpuX/tools/compilers/mg-lcg-clang++-16.0.3 -o fcheck.exe ./fcheck_sa.o -fopenmp ./fsampler.o -L../../lib -lmg5amc_common -Wl,-rpath,'$ORIGIN/../../lib'  -lgfortran -L../../lib -lmg5amc_gg_ttx_cpp ./CommonRandomNumberKernel.o ./RamboSamplingKernels.o
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin/ld: ./fcheck_sa.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin/ld: failed to set dynamic section sizes: bad value
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

- gcc13 in cuda120 (NB unsupported there) gives this build error
```
ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -O3 -lineinfo -I. -I../../src -I/usr/local/cuda-12.0/include/ -DUSE_NVTX -gencode arch=compute_70,code=compute_70 -gencode arch=compute_70,code=sm_70 -use_fast_math -std=c++17  -ccbin /cvmfs/sft.cern.ch/lcg/releases/gcc/13.1.0-b3d18/x86_64-el9/bin/g++ -allow-unsupported-compiler -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -Xcompiler -fPIC -c -x cu Parameters_sm.cc -o Parameters_sm_cu.o
/usr/include/stdlib.h(140): error: identifier "_Float32" is undefined

/usr/include/stdlib.h(146): error: identifier "_Float64" is undefined

/usr/include/stdlib.h(152): error: identifier "_Float128" is undefined

/usr/include/stdlib.h(158): error: identifier "_Float32x" is undefined

/usr/include/stdlib.h(164): error: identifier "_Float64x" is undefined
```

- gcc13 with CUDA_HOME=none seems to build ok

**Comment by valassi** [comment]
I have extensively worked on the move from icx 2023.1 to 2023.2. The results are in MR #737 which fixes new FPEs #736 #738 and also some tolerance for lower precision #734.

For clang16, that MR #737 includes a few wrapper scripts, but the full tests must still be done. Note that clang16 (available on cvmfs) is not supported by cuda12.0, and some of the issues I saw in a first test probably come from there: it may be better to wait for a later cuda 12.x (or one can test CUDA_HOME=none builds). Note also that some of clang17 is tested internally through icx2023.2. So: clang16+ remains to be done.

For gcc13.1, similarly this is not supported by cuda12.0, which may explain some issues. Again one can wait for cuda 12.x or test CUDA_HOME=none builds. So: gcc13+ remains to be done.

(I do not even mention Apple clang - I am not at all actively testing this compiler).

**Comment by valassi** [comment]
Further fixes for clang16 #1005 (and rocm6.0 #1003) and for gcc14.2 #1004 will be in PR #1006

Keep this open anyway, I still want to upgrade cuda and also try a later icpx
