### ISSUE TITLE
CUDA builds of Parameters.cc get the wrong build flags (eg they fail the HRDCOD=1 build)

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#731]
CUDA builds of Parameters.cc get the wrong build flags (eg they fail the HRDCOD=1 build)

My MR #723 has another issue that went undetected by most tests (and which I only found out in building HRDCOD=1 pp_tt_W to test #701 manually): non-SM tests also fail HRDCOD=1 tests. This is probably a minor issue. But it went undetected, so the tests should be made stronger/wider. 

We should add heft_gg_h (or another non-SM process with HRDCOD=1) to tput tests and to CI tests, see now #732.

**Comment by valassi** [comment]
See https://github.com/madgraph5/madgraph4gpu/pull/706/commits/9f74a3698e9be57c1797ef4454fd2833d795cac6 for one of the last commits of #723 
```
Now launching fails with a new build error (in cuda)
HRDCOD=1 tlau/lauX.sh -CPP nobm_pp_ttW

            ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -fPIC -c -x cu Parameters_sm_no_b_mass.cc -o Parameters_sm_no_b_mass_cu.o
            In file included from Parameters_sm_no_b_mass.cc:15:
            Parameters_sm_no_b_mass.h:26:2: error: #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (https://github.com/madgraph5/madgraph4gpu/issues/439): please run "make HRDCOD=1"
               26 | #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (https://github.com/madgraph5/madgraph4gpu/issues/439): please run "make HRDCOD=1"
                  |  ^~~~~

Since I want to use CPP only, I retry disabling also CUDA:
```

**Comment by valassi** [comment]
The same error can be simply detected in heft
```
ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -fPIC -c -x cu Parameters_heft.cc -o Parameters_heft_cu.o
In file included from Parameters_heft.cc:15:
Parameters_heft.h:26:2: error: #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (#439): please run "make HRDCOD=1"
   26 | #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (#439): please run "make HRDCOD=1"
      |  ^~~~~
```

**Comment by valassi** [comment]
In upstream/master this was
```
ccache /cvmfs/sft.cern.ch/lcg/releases/gcc/11.2.0-ad950/x86_64-centos8/bin/g++  -O3  -std=c++17 -I.  -fPIC -Wall -Wshadow -Wextra -ffast-math  -fopenmp -march=skylake-avx512 -mprefer-vector-width=256  -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_FPTYPE2_DOUBLE -DMGONGPU_HARDCODE_PARAM -c Parameters_heft.cc -o Parameters_heft.o
```

In MR #723 this was
```
ccache /usr/local/cuda-12.0/bin/nvcc   -Xcompiler -fPIC -c -x cu Parameters_heft.cc -o Parameters_heft_cu.o
In file included from Parameters_heft.cc:15:
Parameters_heft.h:26:2: error: #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (#439): please run "make HRDCOD=1"
   26 | #error This non-SM physics process only supports MGONGPU_HARDCODE_PARAM builds (#439): please run "make HRDCOD=1"
      |  ^~~~~
```

WELL. The difference is that the namespace MR has introduced the build of this file separately for CUDA. This was not built separately for CUDA before.
