### ISSUE TITLE
error: identifier "MG5_sm::one" is undefined in device code

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#291]
I am having issues with the constexpr 'one', 'two' and 'half' that I had defined in HelAmps.cc.

At some point I had added __device__ in front of constexpr, but I did not remember the reason. This was working ok with cuda 11.4, but then when I moved back to cuda 11.0 (which I did to study the regressions #277 and #282) it was giving me build errors saying I should not __device__ (or maybe the reaons was something else, I do not remember). Anyway, the old code including golden tags was not working on cuda 11.0/gcc9, so I did a patch https://github.com/madgraph5/madgraph4gpu/commit/4e52ad8046550e84c5275d496da4bd14631c94f9

The above was for ggttgg, which was working fine, on 11.0/gcc9. Then hoevwer I regenerated eemumu, and this is giving me build errors (with cuda 11.4 this time), where the 'one' is used,
```
ccache /usr/local/cuda-11.4/bin/nvcc  -O3  -lineinfo -std=c++17 -I. -I../../src -I../../../../../tools -I../../../../../tools -I/usr/local/cuda-11.4/include/ -DUSE_NVTX -arch=compute_70 -use_fast_math -ccbin /cvmfs/sft.cern.ch/lcg/releases/gcc/10.2.0-c44b3/x86_64-centos7/bin/g++ -DMGONGPU_FPTYPE_DOUBLE -DMGONGPU_CURAND_ONDEVICE -c gCPPProcess.cu -o gCPPProcess.o
../../src/HelAmps_sm.cc(951): error: identifier "MG5_sm::two" is undefined in device code
...
../../src/HelAmps_sm.cc(1024): error: identifier "MG5_sm::one" is undefined in device code
...
```

I assume that this was the reason why I had added the __device__ in the first place moving to cuda 11.4. What I find strange is that with cuda 11.4 the ggttgg does not comaplin...

Anyway, I need to find a way to use both versions of cuda, on all processes. Working on code generation that defines these INSIDE the FFV functions (possibly, only if needed).

**Comment by valassi** [comment]
This is now fixed in codegen in https://github.com/valassi/madgraph4gpu/commit/8860f78b6431b1d1c73cd95ac27113e84bab65a8 for PR #281. All code has been regenerated, too.

Now one/two/half are only defined n the FFV functions and only when needed.
This can be closed.
